### ISSUE TITLE
About npm problem

### ISSUE THREAD

**Issue by fxsh1301** [sandeepmistry/node-sx127x#1]
Hi sir ! Thanks for sharing the code for Raspberry Pi.
I met some problem when i was installing node-sx127x
Here's the steps I did and the error message :

pi@raspberrypi:~ $ sudo npm install sx127x
pi@1.0.0 /home/pi
└── sx127x@0.0.0

npm WARN pi@1.0.0 No description
npm WARN pi@1.0.0 No repository field.
pi@raspberrypi:~ $ cd sx127x/node-sx127x-master/
pi@raspberrypi:~/sx127x/node-sx127x-master $ ls
API.md  examples  index.js  lib  LICENSE  npm-debug.log  package.json  README.md
pi@raspberrypi:~/sx127x/node-sx127x-master $ cd examples/
pi@raspberrypi:~/sx127x/node-sx127x-master/examples $ ls
npm-debug.log  receiver.js  sender.js
pi@raspberrypi:~/sx127x/node-sx127x-master/examples $ node receiver.js
open { Error: ENOENT, No such file or directory
    at Error (native) errno: 2, code: 'ENOENT', syscall: 'open' }
/home/pi/sx127x/node-sx127x-master/examples/receiver.js:14
    throw err;
    ^

Error: ENOENT, No such file or directory
    at Error (native)

**Comment by sandeepmistry** [comment]
@fxsh1301 try running the `npm install` in a directory not names `sx127x`.

**Comment by fxsh1301** [comment]
Sorry, I still don't understand what do you mean.
Would you describe more accurately ?
Thanks!
