### ISSUE TITLE
Can't receive from Arduino to Pi

### ISSUE THREAD

**Issue by fxsh1301** [sandeepmistry/node-sx127x#4]
Hi sir !
I solved npm problem by update it.
The sender.js is worked and receive by Arduino with Lora module.
But receiver.js can not receive Arduino's data .
The code work without any error msg.
What problem it might be? 
Thanks!

**Comment by sandeepmistry** [comment]
This is working for me, make sure you have the same radio parameters set up on both sides and the the Arduino is able to supply at least 120 mA's from it's 3.3V power source.
