### ISSUE TITLE
sx1276 with LNS

### ISSUE THREAD

**Issue by gaston33** [sandeepmistry/node-sx127x#9]
Hello,
I'm using the SX-1726 with raspberry pi 3.
I want to join my card to the LoraWAN server ,so i need to send a join_request and I can't find a function in the API to do this job. 
Any help ?

**Comment by sandeepmistry** [comment]
@gaston33 this library only deals with the lower level LoRa stack and not LoRaWAN.

It would be more of a lower level library to build a LoRaWAN stack on top of.
